### ISSUE TITLE
Incompatable with FastCraft

### ISSUE THREAD

**Issue by kuzuanpa** [Asek3/DraconicMinus-#3]
---- Minecraft Crash Report ----
// Don't be sad. I'll do better next time, I promise!

Time: 2022-09-29 12:44:04 CST
Description: Rendering screen

java.lang.NullPointerException
    at ru.nanolive.draconicplus.DPTessellatorHooks.draw(DPTessellatorHooks.java:36)
    at net.minecraft.client.renderer.Tessellator.func_78381_a(Tessellator.java)
    at fastcraft.U.func_85187_a(F:148)
    at unicodefontfixer.FontRendererEx.drawStringChecked(FontRendererEx.java:77)
    at unicodefontfixer.FontRendererEx.func_78261_a(FontRendererEx.java:109)
    at net.minecraft.client.gui.Gui.func_73732_a(SourceFile:95)
    at lumien.custommainmenu.gui.GuiCustom.func_73863_a(GuiCustom.java:386)
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:3044)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Screen render details --
Details:
    Screen name: lumien.custommainmenu.gui.GuiCustom
    Mouse location: Scaled: (36, 119). Absolute: (72, 240)
    Screen size: Scaled: (427, 240). Absolute: (854, 480). Scale factor of 2
Stacktrace:
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:3044)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

and when I remove fastcraft, game works normally without crash.

**Comment by Asek3** [comment]
Update to 1.3R, now should work
